### ISSUE TITLE
Plugin got deleted before being merged

### ISSUE THREAD

**Issue by kazum1kun** [matortheeternal/zedit#101]
This report pertains to zEdit/zMerge 0.5.3, latest release as of date.

I tried to merge two esp's and named the new merge the same as one of the original (e.g. mk14.esp & mk14-awkcr.esp ---> mk14.esp). zEdit said the original (in this case mk14.esp) would be deleted after generating the merge, but in reality it went in reverse - mk14.esp got deleted before merge started and zEdit complained it could not find mk14.esp. 

Can you look into the issue and fix this? Thanks, and I appreciate your effort on this great tool!

**Comment by matortheeternal** [comment]
The warning is there to tell you to not name a merge after a plugin you're merging.  I can update the wording on it to be clearer.

**Comment by kazum1kun** [comment]
Thanks you for the clarification, now it makes sense. However I wonder why it is not possible to name the merge that way? AFAIK Merge Plugins allows me to do that, and since the merge is placed on /merge folder it should not be interfering with the plugin in the FO4 /Data folder. Thanks!

**Comment by matortheeternal** [comment]
It's a limitation of the xEdit framework.  A plugin cannot be created with a filename identical to that of a plugin which is already loaded.  Similarly, a plugin cannot be created with a filename identical to that of a plugin which already exists in the game data folder.  Merge plugins can't do this either.

What you want is effectively "merging upwards", which is a planned future feature.

**Comment by kazum1kun** [comment]
Thanks for the answer mator, good to know!
