### ISSUE TITLE
Gray window on startup

### ISSUE THREAD

**Issue by lex1975** [matortheeternal/zedit#102]
Recently decided to try your program to configure mods in the game Skyrim SE. I downloaded, unpacked into a folder. Launched. I see a gray window, without active elements. No interface elements, only a gray background. You can close the program only through the taskbar. I tried the program version 0.4.3-0.5.4. Error repeats
My system:
Intel Core I7, 16Gb RAM
Windows x64 Professional English SP2 with all updates.
VC++ 2017, Net Framework 4.7.2
Path to program:
D:\prog\TES-V-Skyrim-SE\Skyrim-SE-Tools\zEdit\

zEdit log (D:\prog\TES-V-Skyrim-SE\Skyrim-SE-Tools\zEdit\logs\main_2019_02_04_06_36.txt):

================================================================================
Session started at Mon Feb 04 2019 06:36:02 GMT+0300 (E. Africa Standard Time)

[INFO] Using arch x64
[INFO] Creating windows
[INFO] Creating main window...
[INFO] Main window created
[INFO] Loading application...
[INFO] Window transparency is enabled
[INFO] Progress window is not modal
[INFO] Creating progress window...
[INFO] Progress window created
[INFO] Application loaded.  Showing window.

Session terminated at Mon Feb 04 2019 06:38:08 GMT+0300 (E. Africa Standard Time)
================================================================================

**Comment by lex1975** [comment]
Give me, please, the command line options for logging.
In this guide, I did not find command line options.
https://z-edit.github.io/

I wrote a "gray screen", but probably this is the WSOD - White Screen Of Death ?

**Comment by matortheeternal** [comment]
@lex1975 what windows OS are you on?  You only said `Windows x64 Professional English SP2`, which doesn't tell me if you're on Windows XP, 7, 8, or 10.  My initial thoughts are your OS/antivirus is interfering with the program's ability to read files from its own installation directory.  Try:

1. Running the program as administrator
2. Disabling antivirus programs (including windows defender)
3. Taking ownership of the files in the application's directory

**Comment by lex1975** [comment]
I was wrong. Windows 7 x64 SP1 English Professional with all updates up to 12-2018. VC++ 2017, Net Framework 4.7.2 are installed. Intel Core I7, 16Gb RAM.
There are all rights to the folder D:\Prog\, where Skyrim SE, MO2 and your program zEdit are installed. (read, write, execute)
Does your program launch anything (dll etc.) from the TEMP folder or user profile folder? EMET is enabled with maximum security settings (ASLR, DEP). Applocker is on. There are no problems with other applications. Well, I'll try to disable protection in the evening.

And another request. Give me command line arguments for catching the bug. To enter a more complete error log. Or a test build.

**Comment by lex1975** [comment]
Could you send a 32-bit build for a test on another system?

**Comment by matortheeternal** [comment]
32-bit builds are not supported currently due to issues with chrome's x86 memory management not playing nicely with the XEditLib.dll library.

It does read/write to a folder in `%AppData%\Roaming`, as is standard.

You can try using the `-dev` command line argument to open chrome developer tools when the application starts.

**Comment by lex1975** [comment]
Thanks for the tip (using the -dev command line argument).

In the developer panel, I caught a bug. I created a rule in AppLoker to allow the start of DLLs on a hash.
The application started up normally.

I am not a professional programmer, I am just an advanced user. But I still allow myself to make a comment to you. It is extremely unprofessional to run a dynamic library from the user profile folder. Or, at least warn users in the program description about this feature.

These are two variable-name libraries in the "d:\profiles\alex\AppData\Local\Temp\" folder. Files with extension "tmp.node" which are actually used as dynamically loaded libraries. Usually such libraries should be located in the folder with the executable file of the program.
Their MD5 Hash:
df1d7915f727d3d42f4a266a1d75b1fb
744474bb085d3828db124db3831fea33

**Comment by matortheeternal** [comment]
@lex1975 these libraries are not run due to something in my code, they are simply a part of how Electron works.
