### ISSUE TITLE
[FO4] Advanced Search: "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by ghost** [matortheeternal/zedit#106]
1. Load zEdit up with a Fallout 4 profile.

2. Load up any esp mod.

3. Right click the esp mod and do Advanced Search. 

4. Add a filter (like any of the default ones provided, or searching all paths for the string 'butt')

5. Press 'Search'

![](https://i.imgur.com/rITmhVi.png)

**Comment by matortheeternal** [comment]
looks like the issue is related to the scope you're using, you can try using a custom scope until this is fixed.

**Comment by ghost** [comment]
Interesting. Alright, thanks.
