### ISSUE TITLE
Russian Language Codepage Win-1251 support

### ISSUE THREAD

**Issue by Ne0niq** [matortheeternal/zedit#107]
Dear, honorable, Mator,
Can you please add support for Russian codepage Win-1251? I love your new creation so much and I was so sad when I faced the issue with the Russian version of Skyrim Classic (LE)....

Example of an issue: after merging any .esl-files having win-1251strings inside, I'm getting wrong symbols. Here is a [screenshot after using zMerge](https://i.imgur.com/M6EifIb.png).

Also in zEdit some names are dispayed correcly, but those which supposed to read from the Strings files appearing with such wrong symbols as shown in screenshot. Of course, in Russian version of Skyrim LE he Strings files has codepage win-1251 too.

**Comment by matortheeternal** [comment]
Already completed for v0.6.0.  Please test v0.6.0 when it is released and let me know if it fixes the problems for you.

**Comment by Ne0niq** [comment]
Thank you for your hard work! It seems, currently my job on build the mod set is stopped until update. After I started to work with zEdit/zClean/zMerge I can't go on without it anymore ;)

**Comment by Ne0niq** [comment]
I confirm that zMerge supports Win2151 codepage correctly the updated XEditLib.dll v0.6. Thank you!

**Comment by matortheeternal** [comment]
ok, nice to hear!

**Comment by TalosDx** [comment]
![изображение](https://user-images.githubusercontent.com/9301662/67809913-a7e99c00-faaa-11e9-8cf1-8a86515feb5c.png)
Not work zEdit with module Reproccer Reborn & zEdit's Unified Patching Framework..

**Comment by TalosDx** [comment]
![изображение](https://user-images.githubusercontent.com/9301662/67810003-d4051d00-faaa-11e9-945c-60f6dd556e26.png)
why can't all programs just work with utf-8?

**Comment by TalosDx** [comment]
![изображение](https://user-images.githubusercontent.com/9301662/67810962-b5078a80-faac-11e9-8bef-5e9e135f29b0.png)
After enable beta support utf-8 in win 10 settings:
![изображение](https://user-images.githubusercontent.com/9301662/67810908-9d300680-faac-11e9-991a-fae3b9f5e4d8.png)

**Comment by Ne0niq** [comment]
The UTF8 beta feature in Windows 10 does not work in English version of Windows 10 and making all Russian letters unreadable. It's too early to use this feature, it's work in progress.
