### ISSUE TITLE
Is it possible for an external app to trigger a basic zEdit workflow from end to end without human intervention?

### ISSUE THREAD

**Issue by leontristain** [matortheeternal/zedit#108]
Hi,

Not really an issue, just like to ask a question. Sorry if this isn't the right place for it.

Is it possible to load an esp, run a zEdit automation script on it to make modifications, and then save the esp, from end to end entirely without human intervention, and have the process triggered programmatically?

I'm writing a python script that tries to automate some of the manual things I do when modding Skyrim. I can create/copy any needed files and run command line executables with any cli argument. I'm also prepared to supply zEdit scripts myself, but for the whole thing to work zEdit needs to be runnable from end to end without human intervention. Is this currently doable?

Thanks,
leontristain

**Comment by matortheeternal** [comment]
> Is it possible to load an esp, run a zEdit automation script on it to make modifications, and then save the esp, from end to end entirely without human intervention, and have the process triggered programmatically?

This is completely possible, but running the application headless isn't currently supported and isn't a priority on the dev roadmap.

I'd recommend binding [XEditLib.dll](https://github.com/matortheeternal/xedit-lib) in the language of your choice or make a NodeJS CLI application using [xelib](https://github.com/matortheeternal/xelib).

**Comment by leontristain** [comment]
Thanks for the quick answer!
