### ISSUE TITLE
Zedit profiles not adding

### ISSUE THREAD

**Issue by Scarehawke** [matortheeternal/zedit#109]
So when I first installed Zedit (added it to modorganizer 2) it came with a few games already found.  I wanted to add skyrimVR manually however the profile path remained red and it seems like it's not being detected.  I tinkered a bit and even removed other profiles like fallout 4.  When I tried adding it again it's path also turned red.  All I can think of is that it's not allowed to be in program files?  Any way to fix this issue?

**Comment by matortheeternal** [comment]
SkyrimVR is not yet officially supported.
