### ISSUE TITLE
Merged patch failed to build

### ISSUE THREAD

**Issue by v1lev** [matortheeternal/zedit#112]
I've followed Lexy's guide and tried to build the following merged patch: https://wiki.nexusmods.com/index.php/User:Darkladylexy/Lexys_LOTD_SE_Merge_Page#World_Encounter_Addon_Patches_Merged
zEdit always fails during the master's removal process 
![изображение](https://user-images.githubusercontent.com/17381452/54307870-2827c380-45e6-11e9-929c-d617e238848a.png)
Log: https://pastebin.com/n5AY1hCP

Edit: It caused by Qw_ACE_BSHeartland Patch.esp

**Comment by matortheeternal** [comment]
Change the merge method or use zEdit v0.5.3
