### ISSUE TITLE
Cant see half the features of the app. Just a black screen mostly.

### ISSUE THREAD

**Issue by greyscren** [matortheeternal/zedit#116]
This is what I get, latest version loaded through MO2.
Win 10.
All vcredist, dx, etc

![zEdit_2019-04-20_07-35-38](https://user-images.githubusercontent.com/49804467/56453319-1c47c380-6341-11e9-9736-57bb34d1b94d.png)

**Comment by matortheeternal** [comment]
You can open the inspector with Ctrl+Shift+I to see where the error is happening.  Most likely the issue is zEdit doesn't have access to read files from its own folder.  Try installing it somewhere where you have right access, disabling AV, etc.

**Comment by greyscren** [comment]
> You can open the inspector with Ctrl+Shift+I to see where the error is happening. Most likely the issue is zEdit doesn't have access to read files from its own folder. Try installing it somewhere where you have right access, disabling AV, etc.

Ctrl+Shift+I doesnt do anything for me.
I tried running it as admin but then MO2 starts crying about elevation.
I dont know why. Because I am the only user on the PC and have full elevation so idk.

**Comment by matortheeternal** [comment]
You need MO2 to be run as admin.  You can try running it outside of MO2 as a test as well.  Where do you have the application installed?

**Comment by greyscren** [comment]
> You need MO2 to be run as admin. You can try running it outside of MO2 as a test as well. Where do you have the application installed?

Both MO2 and zedit are on B:\Tools

Shouldnt need elevation.

If I add "Run as admin" on MO2 it keeps complaining and wont function properly.



App directory: B:\Tools\zEdit\resources\app.asar
/B:/Tools\zEdit\themes\day.css Failed to load resource: net::ERR_FILE_NOT_FOUND


Running it as admin outside of MO2 gives the same result.

The day.css file is in the location provided though.

**Comment by matortheeternal** [comment]
Based on the information you have provided your issue must be Windows 10 or an antivirus program blocking the application from reading files from disk.  That could include Windows Defender.

**Comment by greyscren** [comment]
Ok so, for some reason, if I put it in B:\ it wont work.
But in E:\ it works just fine.

Strange issue. maybe the app doesnt like B:\ or # symbol in the path.

**Comment by matortheeternal** [comment]
It's possible that the `#` symbol could interfere with things, yes.  Different partitions can have different permissions associated with them, so that is also possible.  Glad to hear you managed to find a workaround.
