### ISSUE TITLE
Grey screen of Death?

### ISSUE THREAD

**Issue by B-A-Anderson** [matortheeternal/zedit#120]
So I've been searching through the issues for a couple hours now and while I've seen some similar issues I haven't been able to find one that helped me fix my issue. If there is already a fix to this issue please link it to this and I'll be on my way :) In any case. Everytime I try to use Skyrim SE I get the screen of death. For Edit, Clean, or Merge I simply can't get anything to work with Skyrim. I also have fallout 4 on my cpu and that works just fine which is even more annoying. I tried turning off my virus defense program and windows defender but no luck there. I found the logs... But they don't seem to say anything.

Session started at Thu Apr 25 2019 10:13:23 GMT-0400 (Eastern Daylight Time)

[INFO] zEdit v0.6.4 x64
[INFO] Initializing xelib with "F:\Games\Vortex\XEditLib.dll"
[INFO] xelib v0.6.0.0 initialized successfully
[INFO] xelib working directory: "F:\Games\Vortex\"
[INFO] Loading modules...
[INFO] Loading module unifiedPatchingFramework v1.5.1
[INFO] Modules loaded
[INFO] Loading deferred modules...
[INFO] Deferred modules loaded
[INFO] User selected profile: SSE

Also I tried running the dev console, but once I click start session it claims that 'Devtools' disconnected and is of no use. 

This is my first time posting here and it sucks that its a bug. I used MergePlugins for a little while and that was amazing so I'm looking forward to trying this as well. Keep up the good work!

**Comment by paulhlschr** [comment]
The same is happening for me. Trying to use zMerge for Skyrim SE 1.5.73.0, but I get just a grey screen after clicking of "Start session". The window is fully responsible to drag-and-drop and right-clicking, but nothing is rendered except the background.

### Main Log File
```
Session started at Fri May 10 2019 14:54:32 GMT+0200 (Mitteleuropäische Sommerzeit)

[INFO] Using arch x64
[INFO] Creating windows
[INFO] Creating main window...
[INFO] Main window created
[INFO] Loading application...
[INFO] Window transparency is enabled
[INFO] Progress window is not modal
[INFO] Creating progress window...
[INFO] Progress window created
[INFO] Application loaded.  Showing window.

Session terminated at Fri May 10 2019 14:57:54 GMT+0200 (Mitteleuropäische Sommerzeit)
```

### App Log File
```
Session started at Fri May 10 2019 14:54:33 GMT+0200 (Mitteleuropäische Sommerzeit)

[INFO] zEdit v0.6.4 x64
[INFO] Initializing xelib with "E:\Modding\Skyrim\Tools\zEdit\XEditLib.dll"
[INFO] xelib v0.6.0.0 initialized successfully
[INFO] xelib working directory: "E:\Modding\Skyrim\Tools\zEdit\"
[INFO] Loading modules...
[INFO] Loading module unifiedPatchingFramework v1.5.1
[INFO] Modules loaded
[INFO] Loading deferred modules...
[INFO] Deferred modules loaded
[INFO] User selected profile: Skyrim SE
```

**Comment by matortheeternal** [comment]
This happens if a plugin file is corrupted and causes a low-level exception.
