### ISSUE TITLE
No styling applied?

### ISSUE THREAD

**Issue by NMJohns** [matortheeternal/zedit#132]
Hard to say what's going on. I just downloaded the latest version and I'm having issues running it. When launching it, everything looks like: 
![image](https://user-images.githubusercontent.com/11442735/58438652-7dc42600-8095-11e9-83e8-97db3733ce0b.png)

I'm not able to get to the settings menus and whatnot.

Additional info: Win10 pro, relatively new installation... I don't know what info you need honestly.

**Comment by NMJohns** [comment]
Also, I tried the current and the version before current. Both do this.


I feel like I'm missing a prereq or something?

**Comment by matortheeternal** [comment]
your os/antivirus is blocking the application from reading files from disk

**Comment by NMJohns** [comment]
I've white listed the entire folder for zEdit, and also completely turned off my AV. I'm using the default windows defender without any modifications to the settings. I'm not sure what else I would need to do in order to run this program.

**Comment by matortheeternal** [comment]
try installing the application to a folder where you have complete access, like your desktop and see if that changes things

**Comment by NMJohns** [comment]
OK, this works. Permissions-wise I am an administrator on my computer and also the drive that I was attempting to run from was set to full control for all authenticated users(I just double checked again). So what in the world am I missing here that causes zEdit to not function correctly from that drive? I'm concerned other applications will function poorly or not at all as well. I have all my Steam games installed on that drive and they run fine though.
