### ISSUE TITLE
[ERROR] Fixes [Merged] failed to build

### ISSUE THREAD

**Issue by ravensm** [matortheeternal/zedit#134]
[[ERROR] Fixes [Merged] failed to build.txt](https://github.com/z-edit/zedit/files/3243171/ERROR.Fixes.Merged.failed.to.build.txt)

Any help? ive never used this program before

**Comment by matortheeternal** [comment]
It looks like you have the disable mods integration enabled but zEdit couldn't find your modlist.txt file.  Try just disabling the integration on the merge settings tab, integration section.

**Comment by ravensm** [comment]
sweet worked!

**Comment by matortheeternal** [comment]
:+1:
