### ISSUE TITLE
Hit with an Error after Merge is complete

### ISSUE THREAD

**Issue by Darkmega18** [matortheeternal/zedit#141]
I was hit by this stinker after completing a moderate sized merge of some fairly spread out but small tweak like mods. Within the log there was something about being unable to remove a master. but even after I get rid of the ones that it throws those for it still hits me with it. (The mods in question being two mods that I have to get off the steam workshop cause they don't exist on nexus, incase it matters.)

My loader is Vortex. and it worked for my prior 3 smaller merges without any hitches. So I'm just not sure what this error is about so I'm not sure how to proceed. Since the merge appears to be built and in a folder ready, but given that it chucks this at me, I'm not sure if it actually worked properly or not.

![image](https://user-images.githubusercontent.com/8104689/59629797-fa26c200-9186-11e9-9b05-c7e94c066903.png)

**Comment by matortheeternal** [comment]
At the bottom of your merge log it will tell you how it failed to remove a master. Try using the clobber merge method.  This error message will be improved in a future version.

**Comment by Darkmega18** [comment]
Clobber seems to have done it. no explosions, no failure to remove masters. Is there a big difference between the two? is one more stable than the other or something? it doesn't really explain it. :V 

although I'm not sure if it worked cause I didn't still have vortex open in the background which didn't agree with the workshop related stuff which is installed differently to all the vortex deployed stuff... but ok, we'll take it.
