### ISSUE TITLE
Failed to copy element 

### ISSUE THREAD

**Issue by Dillon91** [matortheeternal/zedit#142]
I keep running into this issue, this is with mods and without any mods loaded btw. 

[ERROR] Error: Failed to copy element Skyrim.esm\0010FC16 to 1
Load order FormID [0010FC16] can not be mapped to file FormID for file "zPatch"
(0000000000252C6C){XEditLib.dll} [0000000000653C6C] JclDebug.TJclStackInfoList.Create + $10C
(0000000000252858){XEditLib.dll} [0000000000653858] JclDebug.JclCreateStackList + $48
(0000000000252767){XEditLib.dll} [0000000000653767] JclDebug.DoExceptionStackTrace + $77
(00000000002540D2){XEditLib.dll} [00000000006550D2] JclDebug.DoExceptNotify + $92
(0000000000245715){XEditLib.dll} [0000000000646715] JclHookExcept.TNotifierItem.DoNotify + $35
(000000000024595B){XEditLib.dll} [000000000064695B] JclHookExcept.DoExceptNotify + $BB
(0000000000245AAD){XEditLib.dll} [0000000000646AAD] JclHookExcept.HookedRaiseException + $6D
(000000000000F366){XEditLib.dll} [0000000000410366] System.@RaiseAtExcept + $106
(000000000000F391){XEditLib.dll} [0000000000410391] System.@RaiseExcept + $11
(0000000000274141){XEditLib.dll} [0000000000675141] wbImplementation.TwbFile.LoadOrderFormIDtoFileFormID (Line 3054, "wbImplementation.pas" + 17) + $7C
(00000000002ABF62){XEditLib.dll} [00000000006ACF62] wbImplementation.TwbGroupRecord.AddIfMissingInternal (Line 11020, "wbImplementation.pas" + 100) + $48
(00000000002B6694){XEditLib.dll} [00000000006B7694] wbImplementation.TwbElement.AddIfMissing (Line 12377, "wbImplementation.pas" + 27) + $0
(000000000067A0DB){XEditLib.dll} [0000000000A7B0DB] xeElements.CopyElementToFile (Line 860, "xeElements.pas" + 8) + $45
(000000000067F4A4){XEditLib.dll} [0000000000A804A4] xeElements.CopyElement (Line 1735, "xeElements.pas" + 7) + $22
(00000000000085C9){128ac697-3c28-4c00-b8f8-14931e1f5b2a.tmp.node} [00007FFB49DA95C9]
(00000000000003A6){128ac697-3c28-4c00-b8f8-14931e1f5b2a.tmp.node} [00007FFB49DA13A6]
(0000000000433040){node.dll    } [00007FFB038F4040] Unknown function at ?CreateFrameStateFunctionInfo@CommonOperatorBuilder@compiler@internal@v8@@QEAAPEBVFrameStateFunctionInfo@234@W4FrameStateType@234@HHV?$Handle@VSharedFunctionInfo@internal@v8@@@34@@Z + $3650
(0000000000381223){node.dll    } [00007FFB03842223] Unknown function at ucal_equivalentTo_59 + $1763
(0000000000380053){node.dll    } [00007FFB03841053] Unknown function at ucal_equivalentTo_59 + $593
(000000000037FF3B){node.dll    } [00007FFB03840F3B] Unknown function at ucal_equivalentTo_59 + $47B
(00000000002037A1){            } [000003B4E7C047A1]

    at helpers.Fail (E:\SSE Modding\zEdit\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at E:\SSE Modding\zEdit\resources\app.asar\node_modules\xelib\lib\elements.js:164:21
    at helpers.GetHandle (E:\SSE Modding\zEdit\resources\app.asar\node_modules\xelib\lib\helpers.js:80:9)
    at Object.CopyElement (E:\SSE Modding\zEdit\resources\app.asar\node_modules\xelib\lib\elements.js:162:20)
    at eval (eval at value (file:///E:/SSE%20Modding/zEdit/resources/app.asar/app/app.js:749:18), <anonymous>:569:41)
    at Array.forEach (<anonymous>)
    at patchRecords (eval at value (file:///E:/SSE%20Modding/zEdit/resources/app.asar/app/app.js:749:18), <anonymous>:568:28)
    at filesToPatch.forEach.filename (eval at value (file:///E:/SSE%20Modding/zEdit/resources/app.asar/app/app.js:749:18), <anonymous>:594:28)
    at Array.forEach (<anonymous>)
    at loadAndPatch (eval at value (file:///E:/SSE%20Modding/zEdit/resources/app.asar/app/app.js:749:18), <anonymous>:592:26)

Session terminated at Mon Jun 17 2019 17:11:39 GMT-0500 (Central Daylight Time)
================================================================================
Thank  you for all your help!

**Comment by matortheeternal** [comment]
Can you provide some context for this error?  What patcher(s) are you running?

**Comment by Dillon91** [comment]
Probably would have been helpful. Duh.

Experience Mod zEdit Patcher
UPF No Dragon LODs Patcher
hishy-npc-enchant-fix
UPF Opposite Animation Disabler
UPF Cell Encounter Level in Name Patcher
UPF Khajiit Ears Show Patcher
zedit-spell-absorb-fix
zedit-visual-transfer
zedit-water-damage

Thanks again!

**Comment by matortheeternal** [comment]
From what little I can tell, it seems like a patcher is trying to copy a record to the patch plugin which comes from Skyrim.esm, but Skyrim.esm hasn't been added as a master to the patch plugin.  Could you share the complete patching log?  The log can be found in the zEdit logs folder, with the name `progress_<date>.txt`.  This log will tell us exactly which patcher was running when the error occurred so I can look at that patcher and figure out what's wrong with its code.

**Comment by Dillon91** [comment]
Here is that file. Thanks! 

[progress_2019_06_17_16_00.txt](https://github.com/z-edit/zedit/files/3308500/progress_2019_06_17_16_00.txt)

**Comment by matortheeternal** [comment]
thanks for the log.

based on the log it looks like spell records were being patched.  the only patcher you have which patches spells is the zedit-spell-absorb fix.  looking at the code there it doesn't have an explicit CopyElement call, so this error must be happening when UPF is copying a SPEL record.  The only reason for it to happen at this stage is if the zPatch wasn't built properly, which suggests to me you may have too many modules loaded.  Do you have more than 253 active modules loaded in zEdit when you're running the UPF patcher?  UPF only supports up to 253 modules, where ESLs count towards this module limit.

**Comment by Dillon91** [comment]
I get the error regardless of how many plugins I have loaded.

**Comment by matortheeternal** [comment]
What happens if you try to disable the zedit-spell-absorb-fix patcher?  If that fixes it, you can try my fork of the patcher here:  https://github.com/z-edit/zedit-spell-absorb-fix/releases

**Comment by Dillon91** [comment]
I get the same kind of error with the spell absorb fix disabled. 

[progress_2019_06_21_19_42.txt](https://github.com/z-edit/zedit/files/3316385/progress_2019_06_21_19_42.txt)

**Comment by matortheeternal** [comment]
do you have your patch filename set to zPatch instead of zPatch.esp?  Try adding the .esp extension and see if that makes a difference.

**Comment by Dillon91** [comment]
That was it! Thank you so much!
