### ISSUE TITLE
zEdit is not starting

### ISSUE THREAD

**Issue by ZERUELhun** [matortheeternal/zedit#143]
Sadly I cannot provide any more information just that zEdit isn't starting up seemingly.
When I start up nothing happens, but in the task manager is see 3 zEdit exe is running with no visual results.
I tried with previous versions but the result are the same.

**Comment by matortheeternal** [comment]
disable/add exclusion to antivirus and try a different installation location.

**Comment by ZERUELhun** [comment]
Yepp, after I redirected the installation folder it started normally.
