### ISSUE TITLE
Script Handling

### ISSUE THREAD

**Issue by cal2195** [matortheeternal/zedit#147]
Hi there,

Looking at the source code, I can see that zMerge handles the GetFormFromFile calls, but I don't see GetModByName, checkModPresence, and IsPluginLoaded calls being handled anywhere?

Is this a bug, or am I missing something? 😅 

Thanks,
Cal

**Comment by matortheeternal** [comment]
You're missing the fact that it searches and replaces strings in script string tables, allowing it to handle all of those functions properly regardless of whether or not they're passed string literals or variables.  See https://github.com/z-edit/zedit/blob/x64/src/javascripts/Services/merge/relinker.js#L69-L77
