### ISSUE TITLE
zMerge - sort and filter plugins

### ISSUE THREAD

**Issue by hestenet** [matortheeternal/zedit#148]
1. **Sorting** - When actually building merges, it would be extremely useful if the plugin list was sortable by alpha, load order, or other available meta data (is category from the nexus available?) 

2. **Filter** - Similarly rather than just having a search box, having a filter box that would show me all and only the plugins that match my filter terms.

**Comment by matortheeternal** [comment]
You should determine the plugins you want to merge prior to starting zMerge.  zMerge isn't meant to provide you with all of the metadata required to determine what plugins should go in a merge, just prepare the plugins to be merged ahead of time in your mod manager, as it provides sufficient metadata for those decisions.  There isn't a way to generically provide the metadata you're requesting without simply replicating the functionality of a mod manager or piggybacking on files created by specific mod managers.  Such a feature wouldn't be a worthwhile investment of dev time.

**Comment by hestenet** [comment]
I think you've missed my point.

I have a separate spreadsheet of exactly what plugins I want to merge. But when loading in the plugin list in ZMerge I have to manually scroll through 300+ plugins to check the box next to each. It would be much easier if I could sort and filter so that I could compare my list against the spreadsheet of the ones I want to merge.

**Comment by hestenet** [comment]
Even without adding more meta data (and I can see how that might be too much trouble), being able to actually filter down the list based on the search box rather than just search for the first result, and being able to sort (even just alphabetically) would make actually building merges much less time consuming.

**Comment by matortheeternal** [comment]
when plugins are merged the merge acts like all the plugins were loaded in a single contiguous block where the merge was placed.  as such, it's sensible to just reorganize your load order to have all the plugins you're merging all in one spot, as that's how the merge is going to behave anyways.  if you organize your load order in this fashion then you don't have to do any searching.

I don't want to add sort or filter functionality to the plugins list.  The plugins list is already complex enough, the search functionality is sufficient for most use cases.  The only situation where the search isn't going to let you find a plugin in a few keystrokes is when you have a massive number of plugins with long, nearly identical filenames that are all spread out randomly throughout your load order.  I don't think that's a common or realistic use case so I think the current search feature is sufficient.
