### ISSUE TITLE
ZMerge Adding Unnecessary Masters?

### ISSUE THREAD

**Issue by GoldenDarknezz** [matortheeternal/zedit#151]
To give an example of how this happens, I was merging some .esps that all shared the same masters.
To be specific, AKM and AK400. I've added the master of new calibers to both of these plugins **before** they were merged. Then, I merged them together with ZMerge via the "merge down-improved" method. However after checking my new merged plugin, it now contains DLCworkshop02.esm (this isnt even a master in new calibers) and DLCNukaWorld,esm as a master. The only plugin that requires at least nukaworld as a master would be new calibers. Why is the merging process also adding the masters of a master to a merged plugin? 
I've worked around this by simply merging those weapons mods as is. (they only require Fallout4.esm) and then add New Calibers.esp without having all the other DLCs added as a master.

**Comment by matortheeternal** [comment]
zMerge adds all loaded plugins as masters.
