### ISSUE TITLE
zEdit sort by FormID exceeding 255 plugins

### ISSUE THREAD

**Issue by NavLM** [matortheeternal/zedit#152]
When the plugin amount exceeds 255, the "sort by formID" causes the plugins to load in an order different from load order. 

For example:
...
[0F]
[100]
[101]
...
[10F]
[10]
[110]
..
[11F]
[11]

Ideally it should go to FF and then 100.

**Comment by matortheeternal** [comment]
zEdit doesn't properly support loading >255 plugins.
