### ISSUE TITLE
Zmerge fails to create merges because of No Such File or Directory error

### ISSUE THREAD

**Issue by Barerock** [matortheeternal/zedit#163]
Info: I've selected my directories for MO2 correctly, and they are as follows:
MO2 Path: C:\Users\BLUE-1\AppData\Local\ModOrganizer
Mods Path: C:\Users\BLUE-1\AppData\Local\ModOrganizer\SkyrimSE\mods

When I use the detect tool in the integration settings zMerge inputs an incorrect filepath, which hasn't worked as well as the other two (they let zMerge read the filepaths to the plugins correctly).
Detected path: C:\Mod Organizer

My output path is to my overwrite folder as such: 
C:\Users\BLUE-1\AppData\Local\ModOrganizer\SkyrimSE\mods\Overwrite!\zMerges

I am attempting to create an armor merge out of 12 or so mods with 30 directories, asset data copied, and I think 2-4 Bethesda Archives set to extract. I AM running zEdit through MO2, and I have a zEdit_v0.6.4_-_Portable_x64\Tools\zEdit.exe folder set up. 
The error continues no matter what I think to try.

Edit: Skyrim SE with SKSE will no longer run because of an MO2 error saying:
Exectuable not found: C:\Users\BLUE-1\Desktop\Skyrim Mods & T\zEdit_v0.6.4_-_Portable_x64\Tools\zEdit.exe
This is odd because it IS there and why should SKSE need it to run? Apparently either I or the program changed the filepath of my SKSE executable through MO2. I definitely DID NOT change this myself, guaranteed by the distance between the two tools in my list.

[zMerge Errors.txt](https://github.com/z-edit/zedit/files/3958013/zMerge.Errors.txt)

**Comment by matortheeternal** [comment]
I don't think that's your MO2 path.  The "MO2 path" zMerge wants is the path to the directory containing `Mod Organizer.exe`.  The mods path would be the path you provided however, though I don't know why you're storing mods in AppData, must be because of default MO2 instance behavior?

What's in `C:\Mod Organizer` ?

The asterisks in the filename are the problem however.  Asterisks are not valid characters in windows file paths.  Name your merge without asterisks and it will work.

**Comment by Barerock** [comment]
That is indeed my MO2 path, it contains everything related to MO2 except for my utilities. I don't know why I put it in AppData, but it works pretty well and doesn't have any drawbacks
C:\Mod Organizer doesn't exist, that's just seems to be a fill-in. 
I'll try renaming the merge; I was following a tutorial just to make sure I was doing things right and it seemed like a good idea to individualize it from other .esps. 
Thanks for the help! I'll get back to you tomorrow on how these changes go.

**Comment by matortheeternal** [comment]
@Barerock how did it go?

**Comment by Barerock** [comment]
It worked, though the mods I selected are mishmash about their esps, and some aren't even highlighted red as being overwritten by the merge. I'll have to figure it out later. I'm running over 260 scripts right now, so some merges need to happen asap.
