### ISSUE TITLE
[ERROR] Null references while using module Clean

### ISSUE THREAD

**Issue by nwn9** [matortheeternal/zedit#168]
I've selected only deleted or otherwise fault navmeshes to clean in the options.

Here are the errors:

![error](https://user-images.githubusercontent.com/26827032/71782486-9f49a080-2fda-11ea-92c9-d22d29d841e8.png)
![error2](https://user-images.githubusercontent.com/26827032/71782487-9f49a080-2fda-11ea-9af4-8f96a911c146.png)

And here's my loadorder:

[loadorder.txt](https://github.com/z-edit/zedit/files/4023549/loadorder.txt)

Hope it helps.

**Comment by matortheeternal** [comment]
Don't use zClean.

**Comment by nwn9** [comment]
You don't have active plans to develop it?

**Comment by matortheeternal** [comment]
No it's a dead project.  After investing time into research and development my assessment was that cleaning plugins was a lot more trouble than it's worth.  99.999% of the time it's placebo, and the 0.001% of the time it isn't placebo should be resolved by mod authors manually, not by end users.
