### ISSUE TITLE
Deleted .esps after attempting zMerge

### ISSUE THREAD

**Issue by ghost** [matortheeternal/zedit#173]
Attempted a merge, applicated gave an error log, and crashed; .esps are nowhere to be found on my PC.

[main_2020_01_29_20_59.txt](https://github.com/z-edit/zedit/files/4132040/main_2020_01_29_20_59.txt)
[app_2020_01_29_20_59.txt](https://github.com/z-edit/zedit/files/4132041/app_2020_01_29_20_59.txt)
[merge_2020_01_29_21_02.txt](https://github.com/z-edit/zedit/files/4132042/merge_2020_01_29_21_02.txt)

**Comment by matortheeternal** [comment]
you set the merge filename to the filename of a plugin in the merge.  you can't do that.  the program will delete the file before attempting the merge, because every merge gets merged into a fresh new plugin file.
