### ISSUE TITLE
mods missing after using Zmerge

### ISSUE THREAD

**Issue by strife72** [matortheeternal/zedit#193]
hey man sorry to bother you with this but i was using Zmerge earlier and now i have some mods missing from my load order. i made a post about it on reddit but figured id be better coming here.

https://www.reddit.com/r/skyrimmods/comments/htzpgi/mods_missing_after_using_zmerge/

i tried to make a merge and got errors related to the breezehome mod and it kinda just froze so i closed zmerge in task manager which i think might have caused the problem? not 100% sure this was caused by Zmerge but its the only thing i was doing before it happened

**Comment by KleinByte** [comment]
You should not be posting this here. This is not a support forum. 
This is a bug/issue tracker to fix source code issues. Please respect Github and standard support practices.

**Comment by strife72** [comment]
yes and im saying using the software has resulted in my mods being deleted, therefore there is a problem with the software.
you should not be posting here.

**Comment by Gar0npeX** [comment]
The same thing just happend to me right now, I was trying to merge two plugins but the program failed to do that and deleted two mods I was working on. I searched for the files but they're nowhere to be found, this needs to be fixed asap.

**Comment by matortheeternal** [comment]
duplicate, see https://github.com/z-edit/zedit/issues/179#issuecomment-654009081
