### ISSUE TITLE
Error: Failed to clean masters

### ISSUE THREAD

**Issue by JeffreysDA** [matortheeternal/zedit#199]
I've successfully created several merges in the past using zMerge, but during this most recent one, it gets almost completely finished, then displays a message window with a long string of errors. I have no idea what the errors mean of if there is anything that I can do on my end to remedy them. I zipped the logs and dropped them in here. Below is the copy and pasted chunk of the logs that shows the error. If you need more information just let me know.

[ZMerge Logs.zip](https://github.com/z-edit/zedit/files/5238468/ZMerge.Logs.zip)

> 

Cleaning merge masters...
============================================================
Unloading plugins
[ERROR] Enhanced Skyrim failed to build:
Error: Failed to clean masters in: 192
Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
(00000000002535EC){XEditLib.dll} [00000000006545EC] JclDebug.TJclStackInfoList.Create + $10C
(00000000002531D8){XEditLib.dll} [00000000006541D8] JclDebug.JclCreateStackList + $48
(00000000002530E7){XEditLib.dll} [00000000006540E7] JclDebug.DoExceptionStackTrace + $77
(0000000000254A52){XEditLib.dll} [0000000000655A52] JclDebug.DoExceptNotify + $92
(0000000000246095){XEditLib.dll} [0000000000647095] JclHookExcept.TNotifierItem.DoNotify + $35
(00000000002462DB){XEditLib.dll} [00000000006472DB] JclHookExcept.DoExceptNotify + $BB
(000000000024642D){XEditLib.dll} [000000000064742D] JclHookExcept.HookedRaiseException + $6D
(000000000000F366){XEditLib.dll} [0000000000410366] System.@RaiseAtExcept + $106
(000000000000F391){XEditLib.dll} [0000000000410391] System.@RaiseExcept + $11
(0000000000033452){XEditLib.dll} [0000000000434452] System.SysUtils.ConvertErrorFmt + $32
(0000000000034ACD){XEditLib.dll} [0000000000435ACD] System.SysUtils.StrToInt64 + $3D
(000000000020289B){XEditLib.dll} [000000000060389B] wbInterface.TwbFormID.FromEditValue (Line 11298, "wbInterface.pas" + 16) + $0
(000000000020C88F){XEditLib.dll} [000000000060D88F] wbInterface.TwbFormIDChecked.FromEditValue (Line 12895, "wbInterface.pas" + 1) + $11
(00000000001F58A6){XEditLib.dll} [00000000005F68A6] wbInterface.TwbIntegerDef.FromEditValue (Line 8454, "wbInterface.pas" + 4) + $1B
(00000000002A84D0){XEditLib.dll} [00000000006A94D0] wbImplementation.TwbSubRecord.SetEditValue (Line 10612, "wbImplementation.pas" + 17) + $0
(00000000001EDC23){XEditLib.dll} [00000000005EEC23] wbInterface.TwbDef.Assign (Line 6911, "wbInterface.pas" + 2) + $30
(00000000002B751C){XEditLib.dll} [00000000006B851C] wbImplementation.TwbElement.AssignInternal (Line 12503, "wbImplementation.pas" + 4) + $57
(000000000027CAB7){XEditLib.dll} [000000000067DAB7] wbImplementation.TwbContainer.AssignInternal (Line 4020, "wbImplementation.pas" + 17) + $0
(00000000002A4755){XEditLib.dll} [00000000006A5755] wbImplementation.TwbSubRecord.AssignInternal (Line 9812, "wbImplementation.pas" + 86) + $2D
(00000000002B7413){XEditLib.dll} [00000000006B8413] wbImplementation.TwbElement.Assign (Line 12480, "wbImplementation.pas" + 29) + $0
(00000000002BC1E2){XEditLib.dll} [00000000006BD1E2] wbImplementation.TwbSubRecordArray.AssignInternal (Line 13787, "wbImplementation.pas" + 59) + $0
(00000000002B7413){XEditLib.dll} [00000000006B8413] wbImplementation.TwbElement.Assign (Line 12480, "wbImplementation.pas" + 29) + $0
(00000000002BBC7A){XEditLib.dll} [00000000006BCC7A] wbImplementation.TwbSubRecordArray.AssignInternal (Line 13749, "wbImplementation.pas" + 21) + $52
(00000000002B7413){XEditLib.dll} [00000000006B8413] wbImplementation.TwbElement.Assign (Line 12480, "wbImplementation.pas" + 29) + $0
(000000000028788D){XEditLib.dll} [000000000068888D] wbImplementation.TwbMainRecord.AssignInternal (Line 5880, "wbImplementation.pas" + 109) + $35
(00000000002B7413){XEditLib.dll} [00000000006B8413] wbImplementation.TwbElement.Assign (Line 12480, "wbImplementation.pas" + 29) + $0
(00000000002871E6){XEditLib.dll} [00000000006881E6] wbImplementation.TwbMainRecord.AssignInternal (Line 5830, "wbImplementation.pas" + 59) + $0
(00000000002B7413){XEditLib.dll} [00000000006B8413] wbImplementation.TwbElement.Assign (Line 12480, "wbImplementation.pas" + 29) + $0
(00000000002AED0B){XEditLib.dll} [00000000006AFD0B] wbImplementation.TwbGroupRecord.AddIfMissingInternal (Line 11260, "wbImplementation.pas" + 320) + $0
(00000000002B71D4){XEditLib.dll} [00000000006B81D4] wbImplementation.TwbElement.AddIfMissing (Line 12397, "wbImplementation.pas" + 27) + $0
(000000000067BF6B){XEditLib.dll} [0000000000A7CF6B] xeElements.CopyElementToFile (Line 917, "xeElements.pas" + 8) + $45
(0000000000681344){XEditLib.dll} [0000000000A82344] xeElements.CopyElement (Line 1804, "xeElements.pas" + 7) + $22
(0000000000014279){45d58c6e-0957-46a9-b08f-05329eb8aadb.tmp.node} [00007FFB68305279]
(000000000000CDBE){45d58c6e-0957-46a9-b08f-05329eb8aadb.tmp.node} [00007FFB682FDDBE]
(00000000017A9E77){zEdit.exe   } [00007FF67093AE77] Unknown function at ?Unpack@WasmStreaming@v8@@SA?AV?$shared_ptr@VWasmStreaming@v8@@@std@@PEAVIsolate@2@V?$Local@VValue@v8@@@2@@Z + $1EDC27

    at helpers.Fail (G:\ZTools\zEdit v0.6.5 (x64)\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at Object.CleanMasters (G:\ZTools\zEdit v0.6.5 (x64)\resources\app.asar\node_modules\xelib\lib\masters.js:8:17)
    at Object.cleanMasters [as Clean] (file:///G:/ZTools/zEdit%20v0.6.5%20(x64)/resources/app.asar/app/app.js:9441:15)
    at Object.removeMasters (file:///G:/ZTools/zEdit%20v0.6.5%20(x64)/resources/app.asar/app/app.js:9476:69)
    at finalizeMerge (file:///G:/ZTools/zEdit%20v0.6.5%20(x64)/resources/app.asar/app/app.js:9144:28)
    at file:///G:/ZTools/zEdit%20v0.6.5%20(x64)/resources/app.asar/app/app.js:9174:13
    at file:///G:/ZTools/zEdit%20v0.6.5%20(x64)/resources/app.asar/app/app.js:9058:17
    at processQueue (G:\ZTools\zEdit v0.6.5 (x64)\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at G:\ZTools\zEdit v0.6.5 (x64)\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (G:\ZTools\zEdit v0.6.5 (x64)\resources\app.asar\node_modules\angular\angular.js:16884:28)

Session terminated at Thu Sep 17 2020 05:25:21 GMT-0500 (Central Daylight Time)
================================================================================

**Comment by ikarth** [comment]
Sounds like it might be the same issue as #188 and #157.

**Comment by JeffreysDA** [comment]
> Sounds like it might be the same issue as #188 and #157.

You are correct. Switching to Clobber method worked. Thank you.
