### ISSUE TITLE
zMerge: Allow additional attributes in merges.json

### ISSUE THREAD

**Issue by Pickysaurus** [matortheeternal/zedit#205]
Again, something we spoke about on Discord. Currently zMerge cleans up any custom JSON attributes added by other apps (in my case, Vortex). I understand the reason but ask that you consider either allowing a "vortexModId" attribute or perhaps a "mergeMetaData" object to remain intact when the json is passed through the app.

**Comment by matortheeternal** [comment]
Done in https://github.com/z-edit/zedit/commit/4050d34315b23ea4cf938cefc530ea6104c2dac9, will be in next release.  The key is `customMetadata`, and it is initialized to an empty object when a merge is created.

**Comment by matortheeternal** [comment]
Released in v0.6.6.1
