### ISSUE TITLE
A Javascript Error Occurred In The Main Process

### ISSUE THREAD

**Issue by badbonez** [matortheeternal/zedit#231]
I just downloaded 6.6beta and got this error - do not get it with 6.5. 

![image](https://user-images.githubusercontent.com/21347117/130893266-565cc77e-968c-488d-b27b-35c9a262eac2.png)

I get another error when I close the program.

![image](https://user-images.githubusercontent.com/21347117/130893466-d081a590-5989-48be-9330-4ef00a2b6cb9.png)

I have tried deleting the files in the AppData/Roaming/zEdit, but I get the same error.  Is there something I need to update for this version?

Thanks.

**Comment by matortheeternal** [comment]
This has been fixed with a soft update to the release archive.  Please redownload.
