### ISSUE TITLE
"Maximum plugin count of 254 reached" with less than 254 plugins

### ISSUE THREAD

**Issue by termaxima** [matortheeternal/zedit#233]
I guess zEdit cannot see ESL flagged plugins ? Because I definitely have more than 254 ESPs (I have 440) but most are ESL flagged and the game runs completely fine. Would be nice if I could at least force the patches to build

**Comment by Ouack23** [comment]
Search for existing issues before creating new ones !
#94 #114

**Comment by termaxima** [comment]
Fine but please resolve it soon
