### ISSUE TITLE
MO2 prevents Load Order Selection from showing up

### ISSUE THREAD

**Issue by Manic020** [matortheeternal/zedit#24]
Launching and picking a profile basically soft locks the program. The pop-up to select your plugins never shows up. Doesn't happen when run outside of MO2, the list pops up instantly.

I'm using this version of MO2: https://github.com/Helidoc65/modorganizer/

**Comment by matortheeternal** [comment]
Tested with [MO 2.0.7beta](https://github.com/TanninOne/modorganizer/releases/tag/v2.0.7b), everything works fine.

I haven't downloaded Helidoc's build, but if v2.0.7b works and his doesn't it must be a problem with MO.  Please direct your issue to his repository.
