### ISSUE TITLE
Manage Profiles button resets profile dropdown menu

### ISSUE THREAD

**Issue by fireundubh** [matortheeternal/zedit#30]
On the New Session screen, clicking the Manage Profiles button resets the profile dropdown menu.

### Steps to Reproduce
1. Select a profile in the dropdown menu with a non-zero index.
2. Click the Manage Profiles button.
3. Close the Manage Profiles window.

**Comment by matortheeternal** [comment]
This happens to prevent issues with deleting/creating profiles.  Not a bug.
