### ISSUE TITLE
Default Fallout 4 load order does not include Nuka World and Ultra High Resolution plugins

### ISSUE THREAD

**Issue by fireundubh** [matortheeternal/zedit#32]
The Skyrim and Skyrim SE profiles pre-select all vanilla plugins for those games, but the default load order for the Fallout 4 profile leaves DLCNukaWorld.esm and DLCUltraHighResolution.esm unchecked.

**Comment by matortheeternal** [comment]
This sounds like a case-sensitivity issue in XEditLib in the case of DLCNukaWorld.esm, and DLCUltraHighResolution.esm being simply not tracked as a Bethesda DLC file.

**Comment by matortheeternal** [comment]
Should be fixed in https://github.com/matortheeternal/xedit-lib/commit/aab39b22c0c780c4b562a24ab38695b0ee06fbc0

**Comment by matortheeternal** [comment]
Fixed in v0.4.
