### ISSUE TITLE
Toggle Selected and Check Selected in Load Order context menu have same behaviors

### ISSUE THREAD

**Issue by fireundubh** [matortheeternal/zedit#34]
There are two options on the context menu in the Load Order window that have identical behaviors: Toggle Selected and Check Selected. Are these supposed to behave differently? If not, one should be removed.

**Comment by matortheeternal** [comment]
## Check Selected
### Before
![](https://i.imgur.com/IhA9WFG.png)

### After
![](https://i.imgur.com/RyZP4Sz.png)

## Toggle Selected
### Before
![](https://i.imgur.com/qNfYTQJ.png)

### After
![](https://i.imgur.com/k5tn0pv.png)
