### ISSUE TITLE
references is not being filled up

### ISSUE THREAD

**Issue by Gussak** [matortheeternal/zedit#35]
After dragging to right panel, the data of the item is being fully shown, but the references tab is never filled up, no matter where I click neither what I do. Any tip? or needs fix?
I made it sure, it has references, by confirming thru FNVEdit.

PS.: some thx: fist of all, excellent GUI! highly usable and really good looking, it feels good to use it! also the extra facilities like auto select dependencies on startup is quite nice! the shinkable data trees, all cool! thx!

**Comment by matortheeternal** [comment]
The references work fine - you have to build them manually via the right-click context menu.

![](https://i.imgur.com/dYztN29.png)

This is intended behavior to reduce startup time.
