### ISSUE TITLE
Feature Request:  Give a summary of information for records with children

### ISSUE THREAD

**Issue by ForsakenShell** [matortheeternal/zedit#38]
Some group records would do well and lend themselves to having a summary of the child records in the group container line when it is collapsed.

As an example, script properties when collapsed could be formatted as such:
Current expanded: https://github.com/ForsakenShell/RandomFiles/blob/master/FR_zEdit_Collapsed_Summary_Expanded.png
Proposed summary: https://github.com/ForsakenShell/RandomFiles/blob/master/FR_zEdit_Collapsed_Summary_Collapsed.png

**Comment by matortheeternal** [comment]
This is an interesting suggestion, but I don't think it translates well to xEdit's codebase.  Any value displayed in the record view is an "edit value", and part of xEdit's contract is any value which you see here can also be set.  This would be very complicated in this case as we'd basically have to create a completely reversable serializable format for all types of script properties.  At the moment I think the work required to build this exceeds the value delivered to users.

An option which may provide similar value to users is a right-click menu option to "expand all child nodes", which would recursively expand a node and its children (and their children).  This would alllow you to view property information in two clicks (and collapse again in one click).  A hotkey (Ctrl + Shift + Right arrow maybe?) could make it even faster.

**Comment by ForsakenShell** [comment]
I wasn't suggesting specifically for scripts and script properties, they just served as a simple example, there are other element containers that this would be useful for (such as the common 'DATA\Position' in a lot of records).

In any event, I can see the underlying issue and why it would be problematic to implement.  The rapid expand/collapse isn't a 100% analogue, but it would tackle the underlying goal - improve workflow speed and efficiency.
