### ISSUE TITLE
Can't close popup window

### ISSUE THREAD

**Issue by megaloblast** [matortheeternal/zedit#4]
I received an error when I tried to open a region record. Then I received a [blank popup](http://i.imgur.com/X1imeIj.png) that I can't close out of, requiring me to force close the application.

**Comment by matortheeternal** [comment]
Tried to recreate this, it did not occur for me when opening the same record without `Dolomite Weathers.esp` loaded.  Is this bug repeatable for you?

**Comment by megaloblast** [comment]
I haven't been able to reproduce the bug. In fact, even the issue with profiles not loading has resolved, perhaps with rebooting the computer?

**Comment by matortheeternal** [comment]
That's unlikely, it was trying to load them from the wrong folder.  It's possible though that it was able to automatically construct them properly after a restart.

**Comment by matortheeternal** [comment]
Going to close this because it was unrepeatable.
