### ISSUE TITLE
XEditLib.dll - System decimal separator settings breaks floating point values

### ISSUE THREAD

**Issue by al-kira** [matortheeternal/zedit#41]
Hi Mator,
First try to build a patch using your new tool on SkyrimSE.
It launched an error as failed to build 0, zPatch.esp cuz 1.7 not being a valid float value.
Have you ever encountered such this kind of issue?
Also is there any thred to look for any related discussion on that issue?
Thanks for any help.

-Alkira

**Comment by matortheeternal** [comment]
Which patcher were you running, and where did you get it from?

**Comment by al-kira** [comment]
Well I've followed Lexy's LOTD guide for SSE.
She uses zEdit for fixing the NPCs enchanting potions (patcher "NPC enchant fix") being distributed to them properly.
I got the most updated version of the tool from your GitHub: 
https://github.com/matortheeternal/zedit/releases/download/0.3.0/zEdit_Alpha_v0.3.0_-_Portable.7z
and the fix from there (from you again):
https://github.com/matortheeternal/hishy-npc-enchant-fix/tree/mator-master.

BTW I managed to find a solution provided by a user from the Lexys thread.
Solution: By creating an empty plugin in CK-SSE and renaming it "zPatch.esp", zEdit patched correctly.

I am happy with the result but would have solved it by myself (-_-).

I have been using your tools for quite a long time by now and will probably wait for your next zEdit/ Merge Plugins merged tool I have read about (^_^).

Thanks for your quick reply though.
Thank you for providing us with such great tools (xEdit being the best imho). It never hurts to thank someone's amazing work and receiving it neither, right ;-) ?

-Alkira.

**Comment by matortheeternal** [comment]
I see, I think this is due to decimal/floating point parsing issues in XEdit code.  Delphi and xEdit's codebase have given me this problem many times over the years.  It's about time I stamp it out for good.

**Comment by al-kira** [comment]
That would be in its code. But I have only noticed 2 persons having the issue so far.
Why creating an empty plugin makes it happy? I don't see the relation between those 2 but I am limited in my understanding.

Thanks Colin.
Bye.

-Alban.

**Comment by matortheeternal** [comment]
I've done some testing on my end and I wasn't able to recreate this in the latest version of zEdit.  It will be fixed in future zEdit releases which us v0.3+ of xEditLib.dll.

**Comment by al-kira** [comment]
Thanks for investigating.
- Alban.
