### ISSUE TITLE
White Screen after selecting manage patches

### ISSUE THREAD

**Issue by Kahn13** [matortheeternal/zedit#42]
Playing Skyrim.  Accessing zEdit 0.3.0 through latest release of MO2 (on MO2 discord) on Windows 10.
zEdit loads up fine.  I select my profile and load order displays.  Click on OK at bottom of screen and and the next page displays.  When I right click on the left pane and select Manage Patches, I get a white screen and must access task manager to close out the program.  Have no idea what is causing this.

**Comment by matortheeternal** [comment]
Thanks for the report.  Does this only happen when running zEdit through MO2?

**Comment by Kahn13** [comment]
Apologize for the late response.  If I run it on it's own on just the base Skyrim install I can get to building patches, but then it soft locks at 25.7% on filtering armors.  I have tried it with my AV disabled and with the program entered as an exception.  thanks.

**Comment by Kahn13** [comment]
mator,  this new version of zEdit corrected my white screen and npc enchant fix problems I was having.  Thank you so much for your time and efforts!  I can use zEdit now....*and there was much rejoicing*

**Comment by matortheeternal** [comment]
OK, this white screen may have been fixed then.
