### ISSUE TITLE
zEdit does not pickup Bethesda BSAs upon loading

### ISSUE THREAD

**Issue by avoitishin** [matortheeternal/zedit#43]
As confirmed by dev console, Bethesda BSA archives are not loaded in zEdit session. xEdit and MO are loading them as intended. 
zEdit version: 0.2 portable (can't try with 0.3 due to whitescreen issue)
xEdit version: 3.2.1

Edit: might be related to #37 
Edit 2: Moving zEdit into MO folder seem to resolve this. BSAs are now loading correctly.

**Comment by matortheeternal** [comment]
Issue was with MO2.
