### ISSUE TITLE
White Screen of Death (WSOD) after loading plugins

### ISSUE THREAD

**Issue by avoitishin** [matortheeternal/zedit#44]
Seemingly random white screens. Confirmed by multiple users. For some, white screens are fairly consistent where they cannot get past plugin list at all, for others more random at various stages of user actions.

**Comment by matortheeternal** [comment]
[This article](https://www.nylas.com/blog/low-level-electron-debugging/) has some information that may prove useful.

**Comment by matortheeternal** [comment]
I'm going to be making a new build today which will have verbose logging so I can determine when this is happening.  I think it is either happening when calling `GetResultString` or `GetResultArray`, but I'm not sure.

**Comment by matortheeternal** [comment]
For anyone who is experience white screen crashes, try this build using the `-verbose` target line parameter: http://puu.sh/AhyDq.7z

Then send me the app log if a white screen happens.

**Comment by matortheeternal** [comment]
Here's a new build which uses a mutex to make sure a function isn't dispatched to the DLL while it is handling another call.  Please note this build should *only* be used to see if it fixes white screen crashes!  http://puu.sh/AhFzU.7z

**Comment by Guekka** [comment]
With the latest build, I still experiment white screens right after the loading of plugins. The "-verbose" setting is enabled, but from my limited knowledge, I don't see anything wrong. 
![capture](https://user-images.githubusercontent.com/39066502/39721835-015438d6-5241-11e8-92b5-627e57b44895.JPG)
[app_2018_05_07_21_47.txt](https://github.com/matortheeternal/zedit/files/1981244/app_2018_05_07_21_47.txt)
[main_2018_05_07_21_47.txt](https://github.com/matortheeternal/zedit/files/1981245/main_2018_05_07_21_47.txt)

**Comment by matortheeternal** [comment]
@Guekka Thanks for testing.  So this was with the most recently posted build?  (the one from 2 hours ago?)

If so, it's disappointing that the mutex didn't fix the problem, it was a shot in the dark but I was hoping it would work.  :thinking: 

Based on the log it looks like we never actually started to render the main application view.  My thoughts are now along the lines of "maybe we didn't navigate to the page" or "maybe the exception is happening earlier on".  I'll look around and prepare another build for you to test soon.

**Comment by szymonj99** [comment]
Hi. Just tried the last build that you posted up there ^. Just like Guekka, the logs in the zEdit folder seem to be alright? Excuse my ignorance. The white screen issue is still there for me.

**Comment by matortheeternal** [comment]
@szymonj99 The point is the logs are providing me with more log messages that help me to understand where the failure is occurring.  I can't fix the problem until I've identified the cause.  :)

**Comment by Guekka** [comment]
It was effectively from the last build.
Do you have an idea about the non-rendering of the main application ?
There's probably an exception preventing the program to do so, but I don't
think there's anything useful in the logs.

**Comment by szymonj99** [comment]
App Log: https://pastebin.com/GF8Lyvyf Main Log: https://pastebin.com/GY6AUrsv
Got them attached in case you may want them.
What I find weird is that it was working perfectly just this morning, a few hours ago.

**Comment by matortheeternal** [comment]
@Guekka I don't know yet, that's why I'm making another build with more log messages to try to pin down where the problem is occurring.  Based on the log I know you're getting to the main application view (the `edit.html` page).  Just to verify, you do see the loading spinner while it's loading plugins and resources, correct?

Basically, I know right now that the loader is completing.  It sets `$scope.loaded` to true, which should trigger the rendering of the viewport.  This in turn should trigger the rendering of the main application "pane", which will render the treeView, recordView, referencedByView, and logView.  Lots of different code gets executed while these views are rendering, and I can't think of any part of the code that would cause this exception that wouldn't already have shown me something in the log.  What I know is that the main application process is crashing, which usually happens when an exception occurs in a low-level module.  Up until this point I have assumed the exception was happening in my `xelib` native node addon, which binds XEditLib.dll dynamically.  However, due to the fact that we didn't see the tree view starting to get built (in the log messages) I think this is somewhat unlikely.  I'm thinking now the issue may be in Electron, but I'm hoping this new build will provide us with at least ONE log message after the `[INFO] Files loaded in #.###s` message.

http://puu.sh/AhWCZ.7z

**Comment by matortheeternal** [comment]
OK, thanks for the logs.  Unfortunately we still don't have any log messages after files are loaded.

I've been testing more on my system, and I've found a fairly reliable way to recreate the crashes!  If I click my mouse and press keyboard keys as the loader is completing, I can cause a crash ~50% of the time.  This is really interesting!  I'm going to try to make a build which ignores hotkey presses while the loader is active and for one second after it completes and see if it effects things.  If it doesn't then I'll know the problem isn't with hotkeys being triggered too early, it is with the keyboard/mouse presses causing a change in the application's state/event loop.

Until I have another build, you guys should try running zEdit and taking your hands off of your mouse/keyboard while it's loading, just in case.  :+1:

**Comment by matortheeternal** [comment]
OK, doing some more testing I can reliably recreate the issue if I click around the time when the loader completes.  I'm going to see if I can make it so the application ignores all click events while the plugin loader is active.

**Comment by matortheeternal** [comment]
This build appears to have made it so the WSOD (white screen of death) no longer happens on my side.  Please give a try and let me know if it solves the issue for you too!

[zEdit Developer Build - MouseLock.7z](http://puu.sh/AhZPP.7z)

**Comment by matortheeternal** [comment]
OK, seeing as I can recreate this issue now, I'm going to be moving forward with low level electron debugging for this issue.  It may take me a day or two to get everything figured out, so I'll have to ask you all to be patient.  Thanks for helping out with running debug builds.

**Comment by matortheeternal** [comment]
I'm going to note some resources here for my future reference:
https://github.com/electron/electron/blob/master/docs/development/debug-instructions-windows.md

**Comment by Guekka** [comment]
I can confirm that the last build hasn't solved the problem. The WSOD still occurs after the loading. Good luck for your debugging.

**Comment by matortheeternal** [comment]
OK.  Yeah, debugging isn't going well so far.  Trying to build Electron with symbols.  Got v2.0.0 to build, but ran into issues with running zEdit with it (after updating zEdit's Electron and rebuilding native modules for v2.0.0, it failed to load the application at all).  Tried to go back to v1.8.6, and wasn't able to build Electron at all, so I'm going to go back to v2.0.0 and see if I can get it to work.

**Comment by matortheeternal** [comment]
on the plus side, Electron v2.0.0 gave me a backtrace, which is the first real information about this crash:

```
Backtrace:
        IsSandboxedProcess [0x02EEC996+13497350]
        IsSandboxedProcess [0x02EEC927+13497239]
        GetHandleVerifier [0x0196386D+6710989]
        v8::internal::JSArrayBuffer::Setup [0x5FF209F1+465]
        icu_59::Collator::safeClone [0x5FE5DDD4+78084]
        icu_59::Collator::safeClone [0x5FE5E18B+79035]
        icu_59::Collator::safeClone [0x5FE5DFD2+78594]
        (No symbol) [0x1C30629E]
        (No symbol) [0x2FE39430]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38830]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38830]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE38248]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38941]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38248]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE3873D]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x1C33722B]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE3813A]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE385C5]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38354]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE385C5]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE385C5]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE38248]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE385C5]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x2FE385C5]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE38830]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE38354]
        (No symbol) [0x2FE099A9]
        (No symbol) [0x1C307596]
        (No symbol) [0x2FE385C5]
```

**Comment by matortheeternal** [comment]
UPDATE
```
Mator [1:46 PM]
I'm trying to debug a renderer process crash and I'm going through the steps to build a debug build of Electron, running into some issues.  Are there any other good solutions for investigating crashes, or a source of pre-built debug builds that I can use?  I don't want to set up a remote server for crashReporter if possible.

vulture [1:49 PM]
depending on platform, there may be debug symbols available as a separate download https://github.com/electron/electron/releases/tag/v2.0.0 . that wont be as good as building yourself with all the source available, but it might help narrow down a specific function that caused a crash

Mator [1:50 PM]
thank you @vulture

Mator [2:22 PM]
I have a backtrace now, not sure what to do next.  Thinking I need more information and should try to get debug electron to build.

vulture [2:23 PM]
what does it look like? can you paste it?

Mator [2:23 PM]
sure, didn't want to clutter the channel up too much  ^_^
Backtrace:
        WTF::ArrayBufferContents::AllocateMemoryWithFlags [0x0314C996+106] (c:\build\src\third_party\webkit\source\platform\wtf\typed_arrays\arraybuffercontents.cpp:113)
        WTF::ArrayBufferContents::AllocateMemoryOrNull [0x0314C927+16] (c:\build\src\third_party\webkit\source\platform\wtf\typed_arrays\arraybuffercontents.cpp:123)
        blink::`anonymous namespace'::ArrayBufferAllocator::Allocate [0x01BC386D+13] (c:\build\src\third_party\webkit\source\bindings\core\v8\v8initializer.cpp:400)
        v8::internal::JSArrayBuffer::SetupAllocatingData [0x55A709F1+145] (c:\build\src\v8\src\objects.cc:19187)
        v8::internal::`anonymous namespace'::ConstructBuffer [0x559ADDD4+196] (c:\build\src\v8\src\builtins\builtins-arraybuffer.cc:54)
        v8::internal::Builtin_Impl_ArrayBufferConstructor_ConstructStub [0x559AE18B+427] (c:\build\src\v8\src\builtins\builtins-arraybuffer.cc:82)
        v8::internal::Builtin_ArrayBufferConstructor_ConstructStub [0x559ADFD2+50] (c:\build\src\v8\src\builtins\builtins-arraybuffer.cc:66)
        (No symbol) [0x003ADA68]
        (No symbol) [0x2DEBE5E1]

vulture [2:24 PM]
maybe you ran out of memory
which version of electron btw?

Mator [2:25 PM]
2.0.0, but this has been a consistent issue across multiple builds and versions
was using 1.8.6 previously
The bug happens randomly on my machine/user machines.
At first I thought the issue was my native addon which binds a DLL, but I put a bunch of verbose log messages around the calls and the exception occurs at a time when no calls to the native module are taking place, so I think the issue must be something else.

vulture [2:28 PM]
we have a lot of memory allocation failures that cause crashes as well. sometimes it's because chromium is really inefficient at memory with CERTAIN things, and there's a max heap size that is allowed to be allocated. sometimes it's just because memory fragmentation and poor memory management inside chromium (they use their own thing instead of the windows LFH, and it's not great). sometimes even a gc can trigger a crash due to out-of-memory instead of just being a no-op
(this of course is excluding something bad in your app itself)
and yes it seems like an ArrayBuffer is being allocated from js land

Mator [2:31 PM]
:thinking_face: So what would be a good next step?  This affects a not insubstantial portion of my userbase, and can even happen with regularity for some of them.  I'd prefer there be something I can do to fix the issue because it makes my application somewhat unreliable to use.

vulture [2:31 PM]
are you doing anything with like big images or something?

if you can switch to 64-bit electron that may help

Mator [2:34 PM]
switching to 64-bit is possible but would require a some work to recompile my native addon's DLL.  I can try that for sure.
Nothing with big images.  My application uses a DLL to interface with binary files which are basically just databases.  The GUI offers a virtualized tree view and a spreadsheet-like view for viewing records.
At the time when the exception most often occurs javascript shouldn't be working with any large memory allocations.  It's when the DOM is changing, it seems.

vulture [2:41 PM]
increasing max js heap size and switching to 64-bit to reduce the problems with fragmentation may help. we still have to support 32-bit so we essentially just deal with it :confused:

Mator [2:42 PM]
okay :+1:
that will be my next step then.  thank you for your help!
```

**Comment by matortheeternal** [comment]
Alright!  I have created a 64-bit build and haven't had any WSODs on it in my testing so far.  Please test and let me know how it works for you:

[zEdit Developer Build - x64.7z](http://puu.sh/AiIug.7z)

**Comment by szymonj99** [comment]
Hi. With the new dev build and the new xeditlib dll, I still get this issue: https://imgur.com/a/3mUgTdL
That's different to the "Failed to load plugins" at first, with the dev build.

**Comment by Guekka** [comment]
Hello, I have the same issue when I click on "Ok" after selection plugins : https://imgur.com/Eo3upZq

**Comment by matortheeternal** [comment]
OK, I have a new build of XEditLib.dll for 64-bit zEdit.  This build has stack trace support and fixed pointer math for 64-bit pointer size.  Works on my machine (everything always works on my machine though).  Please give it a try and let me know if something goes wrong.

[XEditLib64 - PointerFixes.zip](https://github.com/matortheeternal/zedit/files/1989996/XEditLib64.-.PointerFixes.zip)

**Comment by szymonj99** [comment]
Oh wow! The PointerFixes fixed the issue for me! zEdit launched perfectly for me. Will mess around with it, and report back problems (if any).

**Comment by Guekka** [comment]
Of course, I can't prove it, but I think this bug can be closed, at least until a new report of WSOD is reported. @szymonj99 You should probably post in on the new thread, https://github.com/matortheeternal/zedit/issues/54

**Comment by szymonj99** [comment]
Whoops, You're right. Should have thought about that. My bad! Will make a new issue report now. @Guekka

**Comment by matortheeternal** [comment]
Reopening because need to maintain 32-bit build for MO1 users.
