### ISSUE TITLE
Profiles don't load in Start View

### ISSUE THREAD

**Issue by megaloblast** [matortheeternal/zedit#5]
I have to recreate my profiles each time I open zEdit.exe. The profiles are saved as .json files in the appdata folder, they just don't appear when I launch the executable. 

Also, selecting Skyrim SE defaults to C:\Steam\steamapps\common\Skyrim instead of C:\Steam\steamapps\common\Skyrim Special Edition\

**Comment by matortheeternal** [comment]
Verified, looking into a fix.

**Comment by matortheeternal** [comment]
Fixed in d4464f8.  Fix will be included in the next release.

**Comment by megaloblast** [comment]
Sweet, thank you!
