### ISSUE TITLE
Drag and drop to empty array slot doesn't work

### ISSUE THREAD

**Issue by Aixcalibur** [matortheeternal/zedit#57]
Sorry if this isn't the proper way or channel to leave a bug report, I'm totally new to this. I tried using the latest alpha version of zEdit with Mod Organizer 2 and Skyrim Legendary Edition and I get the following error when I try to drag and drop. In TES5Edit, if I tried the same thing, I'd be asked if I'd like to add one esp as the master to the other.

Screenshot: https://i.gyazo.com/57538ed19851622b2501a62d107fb20e.png

**Comment by matortheeternal** [comment]
Hmm... This is dragging and dropping in the record view?  I haven't seen this before, I'll look into it.

Thanks for the report.

EDIT: Recreated issue with dragging and dropping an array element into an empty array slot.  Is this the situation where you experienced the error?

**Comment by Aixcalibur** [comment]
Yep, that's what I did to get that error. There's also an error if I drag and drop a reference to something that comes from another plugin.

**Comment by matortheeternal** [comment]
:ok_hand: I'll get it fixed for the next release.

**Comment by matortheeternal** [comment]
Resolved in 8c2a1ab.
