### ISSUE TITLE
Plugin saving issue

### ISSUE THREAD

**Issue by megaloblast** [matortheeternal/zedit#6]
Not necessarily an issue with zEdit, but when running zEdit through MO v2.0.8.2, I am unable to save the esp due to failure to create directory.

**Comment by matortheeternal** [comment]
> failure to create directory.

Can you expand?  There should be no directory created when plugins are saved by zEdit.  It just saves plugins into the data directory.  MO should detect the saved plugins and move them to overwrite.

**Comment by megaloblast** [comment]
[http://i.imgur.com/CMDu7Am.png](http://i.imgur.com/CMDu7Am.png ) the issue happens even when I try outside of MO as well. I'm unable to save any changes.

**Comment by matortheeternal** [comment]
Sounds like an issue with file system permissions.  The only directory that gets created when files are saved is the directory for backups.

**Comment by matortheeternal** [comment]
Resolved with Megaloblast on Discord.  Fix will be included in the next build.  If you're experienced this issue and need a a build before then, grab [this](http://puu.sh/xqYE1.7z) (this build only includes a fix for saving plugins, it's otherwise identical to v0.0.1).
