### ISSUE TITLE
No subpixel antialias

### ISSUE THREAD

**Issue by kamicane** [matortheeternal/zedit#62]
The app has subpixel antialias disabled.

![image](https://user-images.githubusercontent.com/7131/43033990-0a211b6e-8cd4-11e8-9240-82ff1d338dfb.png)

To enable it, the BrowserWindow needs a background color:

```js
new BrowserWindow({
  backgroundColor: '#fff' // important for subpixel antialias
})
```

I found out while working on an app and thought I'd share.

**Comment by matortheeternal** [comment]
Fixed for main window, but the progress window can't use this `backgroundColor` hack because it's a transparent window.
