### ISSUE TITLE
ability to filter plugins

### ISSUE THREAD

**Issue by jmdavis** [matortheeternal/zedit#76]
It would be very nice if zedit provided a way to filter the plugins based on their names when choosing which ones to load (similar to xedit). When there are a lot of plugins, it can get very annoying to find the ones you want when there's no way to filter them, and you're basically forced to read through the entire list to find them.

**Comment by matortheeternal** [comment]
Added on `feature/zMerge`, will be included in next release.

**Comment by matortheeternal** [comment]
available in v0.5.0, use ctrl+F
