### ISSUE TITLE
Removing element doesn't mark record as modified

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/zedit#77]

**Comment by piotrmil** [comment]
Thanks for looking into it!

**Comment by matortheeternal** [comment]
XEditLib issue: https://github.com/matortheeternal/xedit-lib/issues/11

**Comment by matortheeternal** [comment]
Resolved in XEditLib.dll.  Will upload a ~~developer~~ build with the fix.

**Comment by matortheeternal** [comment]
[XEditLib v0.4.4](https://github.com/matortheeternal/xedit-lib/releases/tag/0.4.4)

Hotfix release.  Extract just XEditLib.dll to zEdit installation folder.  I'll may make a hotfix zEdit release as well, but because zEdit v0.5.0 will be releasing soon I may not.  Not sure yet.
