### ISSUE TITLE
Advanced search using up all RAM with large modlist

### ISSUE THREAD

**Issue by Adraxas** [matortheeternal/zedit#78]
I was trying to filter by conflict and zEdit ended up using all of my free ram and then freezing.
It ended up using 22-24gb and only got about 25000 records out of 300000+ (not sure how many as it was too much to display the full number)

**Comment by matortheeternal** [comment]
Duplicate of #56.  Please download the latest developer version in Discord or don't use this feature until v0.5.0 goes up (should be up in the next few days).
