### ISSUE TITLE
Installing UPF patchers as archive doesn't work

### ISSUE THREAD

**Issue by ProbablyManuel** [matortheeternal/zedit#79]
Installing UPF patchers as archives through the Manage Extensions modal doesn't work.

If the patcher archive is built like the [example patcher](https://github.com/z-edit/zedit-example-patcher) (patcher is inside folder {patcherId}), installing it will fail with "Error: No module.json found".

If the patcher archive contains the patcher at the top level, it will be incorrectly installed to:
{patcherId}\partials_ (empty folder)
{patcherId}\index.js
{patcherId}\module.json
{patcherId}\partials_settings.html

**Comment by matortheeternal** [comment]
this is a known issue with the current version because of a problem with the archive extraction library used.  it's fixed on master, fix will be included in next build.
