### ISSUE TITLE
Default settings not getting loaded

### ISSUE THREAD

**Issue by epsilon-0** [matortheeternal/zedit#86]
I made a UPF patcher using z-edit and the default settings are not getting loaded for some reason. (I dunno if this is the first patcher using UPF for FO4 :D :D )

Mod: https://www.nexusmods.com/fallout4/mods/35459

Workaround: Go to settings, toggle all settings to incorrect values and reset them to desired values.
zedit can now read the values.

I dunno what is causing this error.

**Comment by matortheeternal** [comment]
Where are your defaults defined?  Defining defaults in the `partials/settings.html` file isn't correct, you need to define them in the `defaultSettings` object defined in the patcher object you pass to `registerPatcher` in `index.js`.

**Comment by epsilon-0** [comment]
Dam sun.
Thanks a lot. That seems to have fixed it.
