### ISSUE TITLE
node-diskusage issue

### ISSUE THREAD

**Issue by Shybert** [matortheeternal/zedit#89]
https://github.com/jduncanator/node-diskusage/issues/32

I was able to build xelib on its own with Node 10, but not together with zEdit, even when I had updated the "diskusage" dependency. https://github.com/z-edit/xelib/pull/4

**Comment by matortheeternal** [comment]
I currently build zEdit with Node 8.x.  If `node-diskusage` still works with Node 8.x with the update then I will accept the PR.

**Comment by Shybert** [comment]
Works fine for me on my PC with Node 8.12.0.

**Comment by jduncanator** [comment]
`node-diskusage` should work with everything all the way back to Node v0.10. Theoretically it should work with v0.8, but I don't test this and can't promise it will always work in v0.8.
