### ISSUE TITLE
Parent master(s) of a plugin are not loaded automatically

### ISSUE THREAD

**Issue by stuemper** [matortheeternal/zedit#9]
xEdit and the CK load up the parent master(s) automatically. In zEdit it results in a "Fatal Error: <Exception: >". But it clearly loads something in the background, because it takes a second the close zEdit (the program closes immediately in the screen where one can choose the profile and nothing is loaded).
Even if this is intended, it would be handy if zEdit could return either to the profile screen or to the selecting load order pop up after displaying a "Fatal Error: <Exception: >" (not only in this case, but also after choosing the wrong parent accidentally). Atm you need to restart zEdit and start anew.

Reproducible with Skyrim Classic 32bit plugins and masters, other games not tested.

**Comment by matortheeternal** [comment]
Not a bug.  Did you read the release notes?

**Comment by stuemper** [comment]
Oh sorry, did not read them completely.
