### ISSUE TITLE
Plugin list taken from wrong place.

### ISSUE THREAD

**Issue by ForisTale** [matortheeternal/zedit#92]
Hi. I have SkyrimVR and use MO2, but plugin list is taken from \AppData\Local\Skyrim Special Edition instead from SVR. This make me copy plugin list to SSE forder before I run zEdit/zMerge if I want correct plugin list.

**Comment by matortheeternal** [comment]
Duplicate of #95.

**Comment by ForisTale** [comment]
You know my post was first so #95 is duplicate of mine not other way.

**Comment by matortheeternal** [comment]
OK, #95 was put together a bit better so I preferred to keep it active instead of this issue.  More importantly, SkyrimVR support is on the roadmap and will be built.  :+1:
