### ISSUE TITLE
Ideas for future release of zMerge via zEdit

### ISSUE THREAD

**Issue by dap1984** [matortheeternal/zedit#96]
Firstly, thank you for this amazing tool. It makes an amateur like me feel like a professional, then I remember all the credit should go to you. So here is the credit! Mucho kudos.

I just have a couple of ideas that will hopefully make things easier in the future, and one of them probably isn't something you can do anything about, but thought I'd throw them out there anyway.

My first thought was to perhaps include a text filter to the Plugins tab when creating a merged plugin? Not a huge deal, but I had to really comb through the list to make sure I had picked all of the relevant plugins I wanted, when a simple filter would have cut the time to a few seconds.

My second idea (which I don't think you have any control over) was to make it so LOOT would recognise when patches have been merged, instead of throwing up warnings telling me I haven't got a patch for particular mods. If this isn't possible, no big deal, just ignore - I might be a bit triggered by all the warnings I'm getting 🤣 

Thanks again for your work, hugely appreciated.

**Comment by matortheeternal** [comment]
> My first thought was to perhaps include a text filter to the Plugins tab when creating a merged plugin? 

A search is available there, press Ctrl+F to show it.

> make it so LOOT would recognise when patches have been merged

That would be up to the LOOT developers.  There are files associated with merges which they can access if they want, but tapping into these files requires knowing mod installation folders and the user to be using MO, MO2, or Vortex.  I'll consider adjusting the API to make this folder a bit easier to access for the potential of such future integrations.

Thank you for your feedback!

**Comment by matortheeternal** [comment]
See #97.
